#ifndef __PROPERTY_IDS_H__
#define __PROPERTY_IDS_H__

enum {
    PROP_ID_PET_POSITION = 1,
    PROP_ID_PET_STATE,
    PROP_ID_PET_ANIMATION,
    PROP_ID_PET_VISIBLE,
    PROP_ID_PET_SIZE,
    PROP_ID_PET_TYPE,
    PROP_ID_PET_LEVEL,
    PROP_ID_PET_EXPERIENCE,
    PROP_ID_PET_MONEY,
    PROP_ID_SHOW_STATS_PANEL,
    PROP_ID_SHOW_BACKPACK_PANEL,
    PROP_ID_SHOW_COLLECTION_PANEL,
    PROP_ID_BACKPACK_UPDATE,
    PROP_ID_COLLECTION_UPDATE,
    PROP_ID_ITEM_ADDED,
    PROP_ID_ITEM_UNLOCKED,
    PROP_ID_ITEM_COLLECTED
};

#endif
