#ifndef __PROPERTY_IDS_H__
#define __PROPERTY_IDS_H__

enum {
    PROP_ID_PET_POSITION = 1,
    PROP_ID_PET_STATE,
    PROP_ID_PET_ANIMATION,
    PROP_ID_PET_VISIBLE,
    PROP_ID_PET_SIZE,
    PROP_ID_PET_TYPE,
    PROP_ID_PET_LEVEL,
    PROP_ID_PET_EXPERIENCE,
    PROP_ID_PET_MONEY,
    PROP_ID_SHOW_STATS_PANEL,
    PROP_ID_SHOW_BACKPACK_PANEL,
    PROP_ID_SHOW_COLLECTION_PANEL,
    PROP_ID_BACKPACK_UPDATE,
    PROP_ID_COLLECTION_UPDATE,
    PROP_ID_ITEM_ADDED,
    PROP_ID_ITEM_UNLOCKED,
    PROP_ID_ITEM_COLLECTED,
    PROP_ID_SHOW_WORK_PANEL,
    PROP_ID_WORK_STATUS_UPDATE,
    PROP_ID_SHOW_FORGE_PANEL,
    PROP_ID_FORGE_COMPLETED,
    PROP_ID_FORGE_UPDATE,  // 添加锻造更新属性ID
    PROP_ID_SHOW_WORK_UPGRADE_PANEL  // 添加显示工作升级面板的属性ID
};

#endif
